In [6]:
import numpy as np
from scipy.linalg import eigh
np.random.seed(42)

# Generate sample data from normal distribution
X = np.random.normal(0, 1, (10, 2))  # 10 points in 2D

# RBF kernel function with σ=1
def rbf_kernel(x, y, sigma=2.0):
    return np.exp(-np.sum((x - y)**2) / (2 * sigma**2))

# Compute full kernel matrix
n = X.shape[0]
K = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        K[i,j] = rbf_kernel(X[i], X[j])

# Select upper block (first 5x5)
m = 5
K_upper = K[:m, :m]

# Compute eigendecomposition of upper block
eigenvals, eigenvecs = eigh(K_upper)

print("Sample Data:\n", X[:5], "\n")
print("Full Kernel Matrix:\n", K, "\n")
print("Upper Block:\n", K_upper, "\n")
print("Eigenvalues:\n", eigenvals, "\n")
print("Eigenvectors:\n", eigenvecs)

Sample Data:
 [[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]
 [ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]] 

Full Kernel Matrix:
 [[1.         0.70621437 0.93433534 0.7795708  0.83976746 0.8792941
  0.66901586 0.52759278 0.73312672 0.6379099 ]
 [0.70621437 1.         0.61683109 0.83540998 0.75868261 0.52271692
  0.22388895 0.28730061 0.5901904  0.25169101]
 [0.93433534 0.61683109 1.         0.58483218 0.92096866 0.98681305
  0.68333091 0.74732308 0.89280861 0.79431726]
 [0.7795708  0.83540998 0.58483218 1.         0.5880396  0.49084384
  0.3256901  0.20480846 0.42083737 0.25481923]
 [0.83976746 0.75868261 0.92096866 0.5880396  1.         0.88065826
  0.44168351 0.70496769 0.95750876 0.60548393]
 [0.8792941  0.52271692 0.98681305 0.49084384 0.88065826 1.
  0.72316316 0.8186585  0.89245658 0.87222345]
 [0.66901586 0.22388895 0.68333091 0.3256901  0.44168351 0.72316316
  1.         0.49079692 0.44173364 0.82145283]
 [0.52759278 0.28730061 0.74732

In [7]:
eigenvals, eigenvecs = eigh(K)
print("Eigenvalues:\n", eigenvals, "\n")
print("Eigenvectors:\n", eigenvecs)

Eigenvalues:
 [6.34771758e-05 1.20897330e-03 6.92202059e-03 2.14067571e-02
 6.51461806e-02 1.69733565e-01 2.55540868e-01 8.32634332e-01
 1.56272348e+00 7.08462035e+00] 

Eigenvectors:
 [[-0.11947472  0.3356347   0.47896333  0.45631626  0.08141111 -0.34701795
   0.30915777  0.2442366  -0.18366298 -0.34559135]
 [ 0.01978045  0.12266364 -0.12667303  0.29436829  0.25163399  0.62687072
  -0.26415917 -0.0806751  -0.53332711 -0.254658  ]
 [ 0.73701932 -0.25109446 -0.29490244  0.04882409  0.23782296 -0.16074646
   0.29111167  0.00898363  0.02086583 -0.36978585]
 [ 0.00231017 -0.10032825 -0.09025463 -0.36417525 -0.2458842  -0.42768375
  -0.43099353  0.27604731 -0.5357113  -0.23841735]
 [-0.21702031 -0.58613858  0.42283913 -0.25039224 -0.11117918  0.19662636
   0.28937975 -0.30590115 -0.13328396 -0.34892842]
 [-0.61125432 -0.00518316 -0.58340068 -0.04615027  0.28041203 -0.14506454
   0.17520579  0.00297934  0.13873366 -0.36637071]
 [ 0.00259787 -0.08723575 -0.09171373  0.07871204 -0.49246945  0.

In [8]:
import numpy as np

# Create two linearly independent vectors
v1 = np.array([1, 2, -1, 0])
v2 = np.array([0, 1, 1, 2])

# Create rank 2 matrix as sum of outer products
A = np.outer(v1, v1) + np.outer(v2, v2)

print("Matrix A:")
print(A)

# Verify symmetry
print("\nIs symmetric:", np.allclose(A, A.T))

# Verify rank
print("Rank:", np.linalg.matrix_rank(A))

# Show eigenvalues to confirm rank
eigenvals = np.linalg.eigvals(A)
print("\nEigenvalues:")
print(eigenvals)

Matrix A:
[[ 1  2 -1  0]
 [ 2  5 -1  2]
 [-1 -1  2  2]
 [ 0  2  2  4]]

Is symmetric: True
Rank: 2

Eigenvalues:
[ 7.00000000e+00  5.00000000e+00 -7.03060394e-16 -3.79446845e-17]


In [10]:
import numpy as np
n = 4
rank = 3
vs = np.random.rand(rank, n) / np.linalg.norm(vs,axis=0)
A = np.sum([np.outer(v,v) for v in vs], axis=0)
A

array([[2.14594826, 0.38055558, 0.78708671, 1.36528921],
       [0.38055558, 0.53460422, 0.06250853, 0.12799884],
       [0.78708671, 0.06250853, 0.52947625, 0.71337118],
       [1.36528921, 0.12799884, 0.71337118, 1.06114977]])

In [14]:
window_size = 2
window = A[:window_size, :]
S11, V11 = np.linalg.eig(window[:, :window_size]) # A11

np.linalg.svd()

(array([2.23130371, 0.44924877]),
 array([[ 0.97575755, -0.2188543 ],
        [ 0.2188543 ,  0.97575755]]))

In [ ]:
from scipy.sparse.linalg import LinearOperator, svds
import numpy as np

def make_operators(S11, V11, ):
    n, m = V.shape
    k = A22.shape[0]
    shape = (n+k, n+k)
    
    # Define Mv operation
    def matvec(x):
        x1, x2 = x[:n], x[n:]  # Split input vector
        # Compute VSV^T x1 efficiently
        t1 = V.T @ x1          # m×1
        t2 = S @ t1            # m×1
        t3 = V @ t2            # n×1
        # Complete multiplication
        return np.concatenate([
            t3 + A12 @ x2,
            A21 @ x1 + A22 @ x2
        ])
    
    # Define M^T v operation
    def rmatvec(x):
        x1, x2 = x[:n], x[n:]
        t1 = V.T @ x1
        t2 = S.T @ t1
        t3 = V @ t2
        return np.concatenate([
            t3 + A21.T @ x2,
            A12.T @ x1 + A22.T @ x2
        ])
    
    return LinearOperator(shape, matvec=matvec, rmatvec=rmatvec)

# Usage:
# M = make_operators(V, S, A12, A21, A22)
# u, s, vt = svds(M, k=6)  # Get 6 largest singular values

In [138]:
np.linspace(1,N,N)

array([1., 2., 3., 4., 5., 6.])

In [282]:
import numpy as np
from scipy.linalg import eig, svd
from scipy.sparse.linalg import eigs, svds
from scipy.sparse.linalg import LinearOperator

np.random.seed(10)

# Parameters
N = 12  # Full matrix size
w = 4  # Window size
keep = w #// 2  # Number of components to keep (1)

# Generate full 4x4 SPD matrix for testing/comparison
Q = np.random.randn(N,N)
Q, _ = np.linalg.qr(Q)
S = np.linspace(1,N,N)**2
Q = Q[:, :4]
S = S[:4]
full_matrix = Q @ np.diag(S) @ Q.T
full_matrix = (full_matrix + full_matrix.T) / 2
print("Full matrix:")
print(full_matrix)

# First window (2x4)
first_window = full_matrix[:w, :]  

# Step 1: First window eigendecomposition (2x2)
S11, V11 = eig(first_window[:w, :w])
idx = np.argsort(S11)[::-1]
S11, V11 = S11[idx], V11[:, idx]

print("\nStep 1 results:")
print("S11:", S11)
print("V11:", V11)

# Step 2: Compute SVD of augmented matrix
S11_sqrt = np.sqrt(np.abs(S11))
S11_invsqrt = np.zeros_like(S11)
mask = S11 > 1e-10
S11_invsqrt[mask] = 1 / np.sqrt(S11[mask])

upper = V11 @ np.diag(S11_sqrt) @ V11.T
lower = first_window[:, w:].T @ V11 @ np.diag(S11_invsqrt) @ V11.T  # Empty for first window
aug_matrix = np.vstack([upper, lower])

U, S, Vt = svd(aug_matrix, full_matrices=False)
V = U[:, :keep]  # This V is now of shape (w, keep)
S = S[:keep]**2

print("\nStep 2 results:")
print("S:", S)
print("V shape:", V.shape)
# raise

# Second window (2x4)
second_window = full_matrix[w:2*w, :]

# Step 3: Expand A11 and use eigs
def matvec(x):
    x = x.reshape(-1)
    result = np.zeros(2*w, dtype=np.float64)
    
    # Upper left block: V S V^T
    result[:w] = (V[:w, :] @ (np.diag(S) @ (V[:w, :].T @ x[:w]))).real
    
    # Lower left block
    result[w:] = second_window[:, w:].T @ x[w:]
    
    return result

def make_operator(new_window, n, w, V, S):
    def matvec(x):
        x = x.reshape(-1)
        result = np.zeros(n*w, dtype=np.float64)

        # First (n-1)w rows: V S V^T part
        V_old = V[:(n-1)*w, :]  # All but last block
        x_old = x[:(n-1)*w]     # First (n-1)w elements

        # Compute V S V^T x for all old blocks at once
        result[:(n-1)*w] = V_old @ (S * (V_old.T @ x_old))

        # Last block: new window direct computation
        result[(n-1)*w:n*w] = new_window @ x[(n-1)*w:n*w]

        # Cross terms between new window and old blocks
        V_last = V[(n-1)*w:n*w, :]
        cross_term_old = V_old @ (S * (V_last.T @ x[(n-1)*w:n*w]))
        cross_term_new = V_last @ (S * (V_old.T @ x_old))

        result[:(n-1)*w] += cross_term_old.real
        result[(n-1)*w:n*w] += cross_term_new.real

        return result
    return LinearOperator((n*w, n*w), matvec=matvec, rmatvec=matvec, dtype=np.float64)

A11_op = make_operator(second_window[:,w:2*w], 2, w, V, S)
S11_new, V11_new = eigs(A11_op, k=2, which='LR')

print("\nStep 3 results:")
print("S11_new:", S11_new)
print("V11_new shape:", V11_new.shape)

# Step 4: Final SVD
S11_sqrt = np.sqrt(np.abs(S11_new))
S11_invsqrt = np.zeros_like(S11_new)
mask = np.abs(S11_new) > 1e-10
S11_invsqrt[mask] = 1 / np.sqrt(np.abs(S11_new[mask]))

def svd_matvec(x):
    n = 2
    x = x.reshape(-1)  # x should be of shape (2*w,)
    result = np.zeros(N, dtype=np.complex128) 
    
    # Upper block (V11 S11^(1/2) V11^T x)
    v_proj = V11_new.T @ x 
    scaled_proj = S11_sqrt * v_proj  
    result[:n*w] = V11_new @ scaled_proj  
    
    # Lower block (A21 V11 S11^(-1/2) V11^T x)
    scaled_proj_inv = S11_invsqrt * v_proj  
    temp = V11_new @ scaled_proj_inv  
    # A12^T consists of two parts:
    # 1. From V[:(n-1)w,:] S V[nw:,:]^T
    v_old_proj = V[n*w:, :] @ (np.diag(S) @ (V[:(n-1)*w, :].T @ temp[:w]))
    # 2. From new_window[:,nw:]^T 
    new_window_proj = second_window[:, n*w:].T @ temp[w:] 
    result[n*w:] = v_old_proj + new_window_proj 
    return result 

def svd_rmatvec(x): 
    n = 2
#     print(x)
    # Split input vector 
    x1, x2 = x[:n*w], x[n*w:] 
    
    # Compute A12 @ x2 efficiently 
    Vn_t_x2 = V[n*w:, :].T @ x2  # N x 1 
    scaled_Vn_t_x2 = np.diag(S) @ Vn_t_x2  # 
    A12_upper_x2 = V[:(n-1)*w, :] @ scaled_Vn_t_x2  # 2 x 1 
    A12_lower_x2 = second_window[:, n*w:] @ x2  # (w,) 
    A12_x2 = np.concatenate([A12_upper_x2, A12_lower_x2])  # (nw,) 
    
    # V11_new^T @ x1
    V11_new_t_x1 = V11_new.T @ x1  # (k,) 
    
    # V11_new^T @ (A12 @ x2)
    V11_new_t_A12_x2 = V11_new.T @ A12_x2  # (k,) 
    
    # Combine with S11 matrices - use proper diagonal matrix multiplication 
    temp = (np.diag(S11_sqrt) @ V11_new_t_x1) + (np.diag(S11_invsqrt) @ V11_new_t_A12_x2)  
    
    # Final multiplication 
    result = V11_new @ temp  # ((n+1)w,) 
    
    return result 

svd_op = LinearOperator((N, 2*w), matvec=svd_matvec, rmatvec=svd_rmatvec, dtype=np.complex128)

# Compute final SVD
U_new, S_new, Vt_new = svds(svd_op, k=keep)

print("S_new:", S_new**2)
print("U_new shape:", U_new.shape)

S = S_new**2
V = U_new

# Third window 
second_window = full_matrix[2*w:3*w, :]
A11_op = make_operator(second_window[:,w:2*w], 2, w, V, S)
S11_new, V11_new = eigs(A11_op, k=2, which='LR')

print("\nStep 3 results:")
print("S11_new:", S11_new)
print("V11_new shape:", V11_new.shape)

S11_sqrt = np.sqrt(np.abs(S11_new))
S11_invsqrt = np.zeros_like(S11_new)
mask = np.abs(S11_new) > 1e-10xv
S11_invsqrt[mask] = 1 / np.sqrt(np.abs(S11_new[mask]))

print("\nFinal results:")
print("S_new:", S_new**2)
print("U_new shape:", U_new.shape)
print("Vt_new shape:", Vt_new.shape)

svd_op = LinearOperator((N, 2*w), matvec=svd_matvec, rmatvec=svd_rmatvec, dtype=np.complex128)

# Compute final SVD
U_new, S_new, Vt_new = svds(svd_op, k=keep)


# For comparison, compute direct SVD of full matrix
U_full, S_full, Vt_full = svd(full_matrix)
print("\nTrue singular values of full matrix:", S_full)

Full matrix:
[[ 1.48604405e+00 -2.61839517e-01 -4.27454002e-01 -1.52978495e+00
   2.23381589e-03 -1.26039315e+00 -2.71057967e-01  4.65693843e-01
  -1.09291356e+00 -3.51548103e-01 -8.99588320e-01  1.44233085e+00]
 [-2.61839517e-01  7.73320626e-01  7.62800499e-01 -1.21876922e-01
  -1.36027019e-01 -7.95920185e-02  9.75537739e-01 -8.56312526e-01
  -5.00670794e-02 -5.19354094e-01  2.16972160e-01 -2.11662860e-03]
 [-4.27454002e-01  7.62800499e-01  2.54580334e+00  3.15612810e-01
   3.57252479e-01 -5.34607635e-02  2.87498751e+00 -7.72597151e-01
  -1.20741631e+00 -3.38209335e-01  2.33380861e+00 -1.23716362e+00]
 [-1.52978495e+00 -1.21876922e-01  3.15612810e-01  2.65965522e+00
   6.38773213e-04  2.03369171e+00 -1.06610832e+00 -1.12710510e+00
   2.52870334e+00  9.25903625e-01 -5.56500813e-01 -2.05291478e+00]
 [ 2.23381589e-03 -1.36027019e-01  3.57252479e-01  6.38773213e-04
   1.81073374e-01 -7.83190276e-02  5.34825242e-01  3.46941226e-01
  -5.48277993e-01  9.95417208e-02  8.24691931e-01 -2.889303

/tmp/ipykernel_3045386/3742931356.py:81: ComplexWarning: Casting complex values to real discards the imaginary part
  result[:(n-1)*w] = V_old @ (S * (V_old.T @ x_old))


In [ ]:
x = x.reshape(-1)
v_proj = V11.T @ x
scaled_proj_inv = S11_invsqrt * v_proj
temp = V11 @ scaled_proj_inv
v_old_proj = V[n*w:, :] @ (np.diag(S) @ (V[:(n-1)*w, :].T @ temp[:(n-1)*w]))
window_proj = window[:, n*w:].T @ temp[(n-1)*w:]
v_old_proj + window_proj

In [ ]:
x = x.reshape(-1)  
v_proj = V11.T @ x 
scaled_proj_inv = S11_invsqrt * v_proj  
temp = V11 @ scaled_proj_inv  
v_old_proj = V[n*w:, :] @ (np.diag(S) @ (V[:(n-1)*w, :].T @ temp[:w]))
window_proj = window[:, n*w:].T @ temp[w:] 
v_old_proj + window_proj 

In [ ]:
print(V[n*w:, :] @ (np.diag(S) @ (V[:(n-1)*w, :].T @ (V11 @ (S11_invsqrt * (V11.T @ np.ones(30).reshape(-1))))[(n-1)*w:])) + window[:, n*w:].T @ (V11 @ (S11_invsqrt * (V11.T @ np.ones(30).reshape(-1))))[(n-1)*w:])

In [291]:
import numpy as np
from scipy.linalg import eig, svd
from scipy.sparse.linalg import eigs, svds
from scipy.sparse.linalg import LinearOperator

def make_operator(new_window, n, w, V, S):
    def matvec(x):
        x = x.reshape(-1)
        result = np.zeros(n*w, dtype=np.float64)

        # First (n-1)w rows: V S V^T part
        V_old = V[:(n-1)*w, :]
        x_old = x[:(n-1)*w]
        result[:(n-1)*w] = V_old @ (S * (V_old.T @ x_old))

        # Last block + cross terms
        result[(n-1)*w:n*w] = new_window @ x[(n-1)*w:n*w]
        V_last = V[(n-1)*w:n*w, :]
        
        cross_term_old = V_old @ (S * (V_last.T @ x[(n-1)*w:n*w]))
        cross_term_new = V_last @ (S * (V_old.T @ x_old))
        
        result[:(n-1)*w] += cross_term_old.real
        result[(n-1)*w:n*w] += cross_term_new.real
        
        return result
    return LinearOperator((n*w, n*w), matvec=matvec, rmatvec=matvec, dtype=np.float64)

def create_svd_operators(V11_new, S11_new, S11_sqrt, S11_invsqrt, second_window, V, S, n, w, N):
    def svd_matvec(x):
        x = x.reshape(-1)
        result = np.zeros(N, dtype=np.complex128)
        
        v_proj = V11_new.T @ x
        scaled_proj = S11_sqrt * v_proj
        result[:n*w] = V11_new @ scaled_proj
        
        scaled_proj_inv = S11_invsqrt * v_proj
        temp = V11_new @ scaled_proj_inv
        v_old_proj = V[n*w:, :] @ (np.diag(S) @ (V[:(n-1)*w, :].T @ temp[:w]))
        new_window_proj = second_window[:, n*w:].T @ temp[w:]
        result[n*w:] = v_old_proj + new_window_proj
        return result

    def svd_rmatvec(x):
        x1, x2 = x[:n*w], x[n*w:]
        
        Vn_t_x2 = V[n*w:, :].T @ x2
        scaled_Vn_t_x2 = np.diag(S) @ Vn_t_x2
        A12_upper_x2 = V[:(n-1)*w, :] @ scaled_Vn_t_x2
        A12_lower_x2 = second_window[:, n*w:] @ x2
        A12_x2 = np.concatenate([A12_upper_x2, A12_lower_x2])
        
        V11_new_t_x1 = V11_new.T @ x1
        V11_new_t_A12_x2 = V11_new.T @ A12_x2
        
        temp = (np.diag(S11_sqrt) @ V11_new_t_x1) + (np.diag(S11_invsqrt) @ V11_new_t_A12_x2)
        result = V11_new @ temp
        
        return result

    return LinearOperator((N, n*w), matvec=svd_matvec, rmatvec=svd_rmatvec, dtype=np.complex128)

# Parameters
N = 12
w = 4
keep = w

# Generate test matrix
Q = np.random.randn(N, N)
Q, _ = np.linalg.qr(Q)
S = np.linspace(1, N, N)**2
Q = Q[:, :4]
S = S[:4]
full_matrix = Q @ np.diag(S) @ Q.T
full_matrix = (full_matrix + full_matrix.T) / 2

# Process first window
print("Processing window 1")
first_window = full_matrix[:w, :]
S11, V11 = eig(first_window[:w, :w])
idx = np.argsort(S11)[::-1]
S11, V11 = S11[idx], V11[:, idx]

# Initial SVD
S11_sqrt = np.sqrt(np.abs(S11))
S11_invsqrt = np.zeros_like(S11)
mask = S11 > 1e-10
S11_invsqrt[mask] = 1 / np.sqrt(S11[mask])

upper = V11 @ np.diag(S11_sqrt) @ V11.T
lower = first_window[:, w:].T @ V11 @ np.diag(S11_invsqrt) @ V11.T
aug_matrix = np.vstack([upper, lower])

U, S, Vt = svd(aug_matrix, full_matrices=False)
V = U[:, :keep]
S = S[:keep]**2
print(f"Eigenvalues: {S}")
print(f"V shape: {V.shape}")

# Main loop for subsequent windows
num_windows = 3 #N // w - 1  # -1 because we already processed first window
for window_idx in range(num_windows):
    n = window_idx + 2  # Current number of windows being processed
    print(f"\nProcessing window {window_idx + 2}")
    
    # Get new window
    current_window = full_matrix[(n-1)*w:n*w, :]
    
    # Create operator for eigendecomposition
    A11_op = make_operator(current_window[:, (n-1)*w:n*w], n, w, V, S)
    S11_new, V11_new = eigs(A11_op, k=keep, which='LR')
    
    # Prepare for SVD
    S11_sqrt = np.sqrt(np.abs(S11_new))
    S11_invsqrt = np.zeros_like(S11_new)
    mask = np.abs(S11_new) > 1e-10
    S11_invsqrt[mask] = 1 / np.sqrt(np.abs(S11_new[mask]))
    
    # Create SVD operator and compute decomposition
    print("V11_new.shape, S11_new.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N")
    print(V11_new.shape, S11_new.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N)
    svd_op = create_svd_operators(V11_new, S11_new, S11_sqrt, S11_invsqrt, 
                                 current_window, V, S, n, w, N)
    U_new, S_new, Vt_new = svds(svd_op, k=keep)
    
    # Update V and S for next iteration
    V = U_new
    S = S_new**2
    
    print(f"Eigenvalues: {S}")
    print(f"V shape: {V.shape}")

Processing window 1
Eigenvalues: [16.  9.  4.  1.]
V shape: (12, 4)

Processing window 2
V11_new.shape, S11_new.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N
(8, 4) (4,) (4,) (4, 12) (12, 4) (4,) 2 4 12
Eigenvalues: [ 1.  4.  9. 16.]
V shape: (12, 4)

Processing window 3
V11_new.shape, S11_new.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N
(12, 4) (4,) (4,) (4, 12) (12, 4) (4,) 3 4 12


/tmp/ipykernel_3045386/1650677963.py:14: ComplexWarning: Casting complex values to real discards the imaginary part
  result[:(n-1)*w] = V_old @ (S * (V_old.T @ x_old))


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 8)

In [302]:
import numpy as np
from scipy.linalg import eig, svd
from scipy.sparse.linalg import eigs, svds
from scipy.sparse.linalg import LinearOperator

def make_operator(window, n, w, V, S):
    def matvec(x):
        x = x.reshape(-1)
        result = np.zeros(n*w, dtype=np.float64)

        # First (n-1)w rows: V S V^T part
        V_old = V[:(n-1)*w, :]
        x_old = x[:(n-1)*w]
        result[:(n-1)*w] = V_old @ (S * (V_old.T @ x_old))

        # Last block + cross terms
        result[(n-1)*w:n*w] = window @ x[(n-1)*w:n*w]
        V_last = V[(n-1)*w:n*w, :]
        
        cross_term_old = V_old @ (S * (V_last.T @ x[(n-1)*w:n*w]))
        cross_term_new = V_last @ (S * (V_old.T @ x_old))
        
        result[:(n-1)*w] += cross_term_old.real
        result[(n-1)*w:n*w] += cross_term_new.real
        
        return result
    return LinearOperator((n*w, n*w), matvec=matvec, rmatvec=matvec, dtype=np.float64)

def create_svd_operators(V11, S11, S11_sqrt, S11_invsqrt, window, V, S, n, w, N):
    def svd_matvec(x):
        x = x.reshape(-1)
        result = np.zeros(N, dtype=np.complex128)
        
        v_proj = V11.T @ x
        scaled_proj = S11_sqrt * v_proj
        result[:n*w] = V11 @ scaled_proj
        
        scaled_proj_inv = S11_invsqrt * v_proj
        temp = V11 @ scaled_proj_inv
#         print(V[:(n-1)*w, :].T.shape, temp.shape, w )
        v_old_proj = V[n*w:, :] @ (np.diag(S) @ (V[:(n-1)*w, :].T @ temp[:(n-1)*w]))
        window_proj = window[:, n*w:].T @ temp[(n-1)*w:]
        result[n*w:] = v_old_proj + window_proj
        return result

    def svd_rmatvec(x):
        x1, x2 = x[:n*w], x[n*w:]
        
        Vn_t_x2 = V[n*w:, :].T @ x2
        scaled_Vn_t_x2 = np.diag(S) @ Vn_t_x2
        A12_upper_x2 = V[:(n-1)*w, :] @ scaled_Vn_t_x2
        A12_lower_x2 = window[:, n*w:] @ x2
        A12_x2 = np.concatenate([A12_upper_x2, A12_lower_x2])
        
        V11_t_x1 = V11.T @ x1
        V11_t_A12_x2 = V11.T @ A12_x2
        
        temp = (np.diag(S11_sqrt) @ V11_t_x1) + (np.diag(S11_invsqrt) @ V11_t_A12_x2)
        result = V11 @ temp
        
        return result

    return LinearOperator((N, n*w), matvec=svd_matvec, rmatvec=svd_rmatvec, dtype=np.complex128)

# Parameters
N = 12
w = 3
keep = w

# Generate test matrix
Q = np.random.randn(N, N)
Q, _ = np.linalg.qr(Q)
S = np.linspace(1, N, N)**2
# Q = Q[:, :4]
# S = S[:4]
full_matrix = Q @ np.diag(S) @ Q.T
full_matrix = (full_matrix + full_matrix.T) / 2

# Process first window
first_window = full_matrix[:w, :]
S11, V11 = eig(first_window[:w, :w])
idx = np.argsort(S11)[::-1]
S11, V11 = S11[idx], V11[:, idx]

# Initial SVD
S11_sqrt = np.sqrt(np.abs(S11))
S11_invsqrt = np.zeros_like(S11)
mask = S11 > 1e-10
S11_invsqrt[mask] = 1 / np.sqrt(S11[mask])

upper = V11 @ np.diag(S11_sqrt) @ V11.T
lower = first_window[:, w:].T @ V11 @ np.diag(S11_invsqrt) @ V11.T
aug_matrix = np.vstack([upper, lower])

U, S, Vt = svd(aug_matrix, full_matrices=False)
V = U[:, :keep]
S = S[:keep]**2
print("Window 1:")
print(f"Eigenvalues: {S}")
print(f"V shape: {V.shape}")

# Main loop for subsequent windows
num_windows = N // w - 1  # -1 because we already processed first window
for window_idx in range(num_windows):
    n = window_idx + 2  # Current number of windows being processed
    print(f"\nProcessing window {window_idx + 2}")
    
    # Get new window
    current_window = full_matrix[(n-1)*w:n*w, :]
    
    # Create operator for eigendecomposition
    A11_op = make_operator(current_window[:, (n-1)*w:n*w], n, w, V, S)
    S11, V11 = eigs(A11_op, k=keep, which='LR')
    
    if window_idx == num_windows - 1:
        # If last window, stop
        V = V11
        S = S11
        print(f"Eigenvalues: {S}")
        print(f"V shape: {V.shape}")
        break
    
    # Prepare for SVD
    S11_sqrt = np.sqrt(np.abs(S11))
    S11_invsqrt = np.zeros_like(S11)
    mask = np.abs(S11) > 1e-10
    S11_invsqrt[mask] = 1 / np.sqrt(np.abs(S11[mask]))
    
    # Create SVD operator and compute decomposition
    print("V11.shape, S11.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N")
    print(V11.shape, S11.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N)

    svd_op = create_svd_operators(V11, S11, S11_sqrt, S11_invsqrt, 
                                 current_window, V, S, n, w, N)
    U, S, Vt = svds(svd_op, k=keep)
    
    # Update V and S for next iteration
    V = U
    S = S**2
    
    print(f"Eigenvalues: {S}")
    print(f"V shape: {V.shape}")

Window 1:
Eigenvalues: [132.20189861 101.41087071  49.80049823]
V shape: (12, 3)

Processing window 2
V11.shape, S11.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N
(6, 3) (3,) (3,) (3, 12) (12, 3) (3,) 2 3 12
Eigenvalues: [ 51.20522467  99.40247132 134.22178835]
V shape: (12, 3)

Processing window 3
V11.shape, S11.shape, S11_sqrt.shape, current_window.shape, V.shape, S.shape, n, w, N
(9, 3) (3,) (3,) (3, 12) (12, 3) (3,) 3 3 12
Eigenvalues: [ 89.91215784 106.36598823 135.44784907]
V shape: (12, 3)

Processing window 4
Eigenvalues: [142.47081749+0.j 118.32848349+0.j  96.54651297+0.j]
V shape: (12, 3)


/tmp/ipykernel_3045386/2287178568.py:14: ComplexWarning: Casting complex values to real discards the imaginary part
  result[:(n-1)*w] = V_old @ (S * (V_old.T @ x_old))


In [303]:
U_full, S_full, Vt_full = svd(full_matrix)
print("\nTrue singular values of full matrix:", S_full)


True singular values of full matrix: [144. 121. 100.  81.  64.  49.  36.  25.  16.   9.   4.   1.]


In [285]:
np.linalg.svd(full_matrix[:4,:])

SVDResult(U=array([[-0.51674311, -0.14595778, -0.33060962,  0.7761251 ],
       [ 0.02406456,  0.26501723, -0.90882792, -0.32127648],
       [ 0.1147453 ,  0.92694952,  0.16053495,  0.31910285],
       [ 0.84807486, -0.22187109, -0.19737683,  0.43884465]]), S=array([6.04476964, 5.31872559, 1.21624605, 0.77866871]), Vh=array([[-3.50819750e-01,  2.28429550e-02,  1.32184130e-01,
         5.09427972e-01,  6.13870035e-03,  3.91739093e-01,
        -6.79438884e-02, -2.16016878e-01,  4.25084041e-01,
         1.51468087e-01,  4.39911903e-02, -4.34813854e-01],
       [-6.45088548e-02,  1.83743137e-01,  4.80256276e-01,
        -2.00346746e-02,  5.53963046e-02, -6.35306141e-02,
         6.01573475e-01, -1.43078585e-01, -2.88416749e-01,
        -1.13798093e-01,  4.65449372e-01, -1.69662095e-01],
       [-1.64527578e-02, -3.86218635e-01, -1.68993944e-01,
         1.16949476e-01,  1.48088509e-01,  6.49930992e-02,
        -1.02792103e-01,  5.94216489e-01, -2.35240132e-01,
         2.88742844e-01,  4.8

In [172]:
full_matrix

array([[ 0.55223763,  0.09539684,  0.26776385, -0.1950996 ,  0.9277204 ,
        -0.28608835],
       [ 0.09539684,  0.01688533,  0.02783035, -0.01133994,  0.14752528,
        -0.04458751],
       [ 0.26776385,  0.02783035,  0.9661488 , -1.10966305,  1.0278644 ,
        -0.35809511],
       [-0.1950996 , -0.01133994, -1.10966305,  1.30094234, -1.02933859,
         0.36733932],
       [ 0.9277204 ,  0.14752528,  1.0278644 , -1.02933859,  1.95803038,
        -0.63223722],
       [-0.28608835, -0.04458751, -0.35809511,  0.36733932, -0.63223722,
         0.20575552]])

In [184]:
second_window[:,n*w:], n ,w

(array([[ 1.0278644 , -0.35809511],
        [-1.02933859,  0.36733932]]),
 2,
 2)

In [251]:
n = 2
upper_block = V11_new @ np.diag(S11_sqrt) @ V11_new.T
    
# Lower block: A21 V11 S11^(-1/2) V11^T
A12_upper = V[:(n-1)*w, :] @ (np.diag(S) @ V[n*w:, :].T)  # First part of A21
A12 = np.vstack([A12_upper, second_window[:, n*w:]])  # Full A21

lower_block = A12.T @ V11_new @ np.diag(S11_invsqrt) @ V11_new.T
    
G = np.vstack([upper_block, lower_block])
G @ G.T

array([[ 0.55223763+0.j,  0.09539684+0.j,  0.26776385+0.j,
        -0.1950996 +0.j,  0.9277204 +0.j, -0.28608835+0.j],
       [ 0.09539684+0.j,  0.01688533+0.j,  0.02783035+0.j,
        -0.01133994+0.j,  0.14752528+0.j, -0.04458751+0.j],
       [ 0.26776385+0.j,  0.02783035+0.j,  0.9661488 +0.j,
        -1.10966305+0.j,  1.0278644 +0.j, -0.35809511+0.j],
       [-0.1950996 +0.j, -0.01133994+0.j, -1.10966305+0.j,
         1.30094234+0.j, -1.02933859+0.j,  0.36733932+0.j],
       [ 0.9277204 +0.j,  0.14752528+0.j,  1.0278644 +0.j,
        -1.02933859+0.j,  1.95803038+0.j, -0.63223722+0.j],
       [-0.28608835+0.j, -0.04458751+0.j, -0.35809511+0.j,
         0.36733932+0.j, -0.63223722+0.j,  0.20575552+0.j]])

In [ ]:
n = 2
upper_block = V11 @ np.diag(S11_sqrt) @ V11.T
    
# Lower block: A21 V11 S11^(-1/2) V11^T
A12_upper = V[:(2-1)*w, :] @ (np.diag(S) @ V[2*w:, :].T)  # First part of A21
A12 = np.vstack([A12_upper, current_window[:, 2*w:]])  # Full A21

lower_block = A12.T @ V11 @ np.diag(S11_invsqrt) @ V11.T
    
G = np.vstack([upper_block, lower_block])
G @ G.T

In [239]:
# Create test vector x
x = np.random.randn((n+1)*w)  # (12,)
x1, x2 = x[:n*w], x[n*w:]     # (8,), (4,)

# Let's verify each step:

# Step 1: G^T @ x = upper_block^T @ x1 + lower_block^T @ x2
step1_direct = G.T @ x
step1_split = upper_block.T @ x1 + lower_block.T @ x2
print("Step 1 verified:", np.allclose(step1_direct, step1_split))

# Step 2: = (V11_new @ S11_sqrt @ V11_new^T) @ x1 + (A12^T @ V11_new @ S11_invsqrt @ V11_new^T)^T @ x2
step2_upper = (V11_new @ np.diag(S11_sqrt) @ V11_new.T) @ x1
step2_lower = (A12.T @ V11_new @ np.diag(S11_invsqrt) @ V11_new.T).T @ x2
step2_combined = step2_upper + step2_lower
print("Step 2 verified:", np.allclose(step1_direct, step2_combined))

# Step 3: = V11_new @ S11_sqrt @ (V11_new^T @ x1) + V11_new @ S11_invsqrt @ (V11_new^T @ (A12 @ x2))
step3_upper = V11_new @ np.diag(S11_sqrt) @ (V11_new.T @ x1)
step3_lower = V11_new @ np.diag(S11_invsqrt) @ (V11_new.T @ (A12 @ x2))
step3_combined = step3_upper + step3_lower
print("Step 3 verified:", np.allclose(step2_combined, step3_combined))

# Step 4: = V11_new @ (S11_sqrt @ (V11_new^T @ x1) + S11_invsqrt @ (V11_new^T @ (A12 @ x2)))
step4 = V11_new @ (np.diag(S11_sqrt) @ (V11_new.T @ x1) + 
                   np.diag(S11_invsqrt) @ (V11_new.T @ (A12 @ x2)))
print("Step 4 verified:", np.allclose(step3_combined, step4))


# Verify all steps are equivalent
print("\nAll steps match G.T @ x:", 
      np.allclose(step1_direct, step1_split) and 
      np.allclose(step1_direct, step2_combined) and 
      np.allclose(step1_direct, step3_combined) and 
      np.allclose(step1_direct, step4))

# Print shapes at key points
print("\nKey shapes:")
print(f"G.T @ x shape: {(G.T @ x).shape}")
print(f"V11_new^T @ x1 shape: {(V11_new.T @ x1).shape}")
print(f"A12 @ x2 shape: {(A12 @ x2).shape}")
print(f"V11_new^T @ (A12 @ x2) shape: {(V11_new.T @ (A12 @ x2)).shape}")
print(f"Final result shape: {step4.shape}")

Step 1 verified: True
Step 2 verified: True
Step 3 verified: True
Step 4 verified: True

All steps match G.T @ x: True

Key shapes:
G.T @ x shape: (4,)
V11_new^T @ x1 shape: (2,)
A12 @ x2 shape: (4,)
V11_new^T @ (A12 @ x2) shape: (2,)
Final result shape: (4,)


In [241]:
step4, step1_direct

(array([ 0.28741493+0.j,  0.04859309+0.j,  0.18732322+0.j, -0.15975616+0.j]),
 array([ 0.28741493+0.j,  0.04859309+0.j,  0.18732322+0.j, -0.15975616+0.j]))

In [254]:
A12 @ x2, A12_x2

(array([ 0.05755226+0.j,  0.01024187+0.j,  0.0142904 +0.j, -0.00380764+0.j]),
 array([ 0.05755226+0.j,  0.01024187+0.j,  0.0142904 +0.j, -0.00380764+0.j]))

In [249]:
V[:(n-1)*w, :] @ np.diag(S) @ V[n*w:, :].T @ x2

array([0.05755226+0.j, 0.01024187+0.j])

In [268]:
# Compute A12 @ x2 efficiently 
Vn_t_x2 = V[n*w:, :].T @ x2  # N x 1
scaled_Vn_t_x2 = np.diag(S) @ Vn_t_x2  # 
A12_upper_x2 = V[:(n-1)*w, :] @ scaled_Vn_t_x2  # 2 x 1 
A12_lower_x2 = second_window[:, n*w:] @ x2  # (w,) 
A12_x2 = np.concatenate([A12_upper_x2, A12_lower_x2])  # (nw,)

V11_new @ (np.diag(S11_sqrt) @ (V11_new.T @ x1) + 
                   np.diag(S11_invsqrt) @ (V11_new.T @ (A12_x2)))

array([ 0.28741493+0.j,  0.04859309+0.j,  0.18732322+0.j, -0.15975616+0.j])

In [269]:
np.random.seed(10)
test_x, test_y = np.random.rand(2*w), np.random.rand(3*w)
G @ test_x, svd_matvec(test_x), G.T @ test_y, svd_rmatvec(test_y)

(array([ 0.62757643+0.j,  0.11533152+0.j, -0.00982107+0.j,  0.1595345 +0.j,
         0.837177  +0.j, -0.2427207 +0.j]),
 array([ 0.62757643+0.j,  0.11533152+0.j, -0.00982107+0.j,  0.1595345 +0.j,
         0.837177  +0.j, -0.2427207 +0.j]),
 array([ 0.53673887+0.j,  0.10386536+0.j, -0.24567242+0.j,  0.42442837+0.j]),
 array([ 0.53673887+0.j,  0.10386536+0.j, -0.24567242+0.j,  0.42442837+0.j]))

In [229]:
def rmatvec(x):
    n = 2
    # Split input vector
    x1, x2 = x[:n*w], x[n*w:]
    
    # Compute A12 @ x2 efficiently
    Vn_t_x2 = V[n*w:, :].T @ x2  # (w/2,)
    scaled_Vn_t_x2 = S * Vn_t_x2  # (w/2,)
    A12_upper_x2 = V[:(n-1)*w, :] @ scaled_Vn_t_x2  # ((n-1)w,)
    A12_lower_x2 = second_window[:, n*w:] @ x2  # (w,)
    A12_x2 = np.concatenate([A12_upper_x2, A12_lower_x2])  # (nw,)
    
    # V11_new^T @ x1
    V11_new_t_x1 = V11_new.T @ x1  # (k,)
    
    # V11_new^T @ (A12 @ x2) 
    V11_new_t_A12_x2 = V11_new.T @ A12_x2  # (k,) 
    
    print("\nIntermediate results:") 
    print("V11_new_t_x1:", V11_new_t_x1.shape, V11_new_t_x1[:4]) 
    print("V11_new_t_A12_x2:", V11_new_t_A12_x2.shape, V11_new_t_A12_x2[:4]) 
    
    # Combine with S11 matrices
    temp = S11_sqrt @ V11_new_t_x1 + S11_invsqrt * V11_new_t_A12_x2  # (k,) 
    
#     print(S11_invsqrt.shape, V11_new_t_A12_x2.shape) 
    # Final multiplication 
    result = V11_new @ temp  # ((n+1)w,) 
#     print(result.shape) 
    return result 

def rmatvec(x): 
    n = 2 
    # Split input vector 
    x1, x2 = x[:n*w], x[n*w:] 
    
    # Compute A12 @ x2 efficiently 
    Vn_t_x2 = V[:(n-1)*w, :].T @ x2  # N x 1
    scaled_Vn_t_x2 = S * Vn_t_x2  # 
    A12_upper_x2 = V[n*w:, :] @ scaled_Vn_t_x2  # 2 x 1
    A12_lower_x2 = second_window[:, n*w:] @ x2  # (w,) 
    A12_x2 = np.concatenate([A12_upper_x2, A12_lower_x2])  # (nw,) 
    
    # V11_new^T @ x1
    V11_new_t_x1 = V11_new.T @ x1  # (k,) 
    
    # V11_new^T @ (A12 @ x2)
    V11_new_t_A12_x2 = V11_new.T @ A12_x2  # (k,) 
    
    # Combine with S11 matrices - use proper diagonal matrix multiplication 
    temp = (np.diag(S11_sqrt) @ V11_new_t_x1) + (np.diag(S11_invsqrt) @ V11_new_t_A12_x2)  
    
    # Final multiplication 
    result = V11_new @ temp  # ((n+1)w,) 
    print(result.shape)
    
    return result 

# Verify dimensions 
test_vec = np.random.rand(3*w) 
# assert rmatvec(test_vec).shape == (2*w,) 

# Print shapes and first few values of key intermediates 
print("Shapes:") 
print(f"V11_new: {V11_new.shape}") 
print(f"S11_sqrt: {S11_sqrt.shape}") 
print(f"S11_invsqrt: {S11_invsqrt.shape}") 
print(f"A12: {A12.shape}") 

# Check the explicit upper and lower blocks 
print("\nFirst few values:") 
print("Upper block first row:", upper_block[0,:4]) 
print("Lower block first row:", lower_block[0,:4]) 

# Verify G.T @ x matches rmatvec(x) 
G.T @ test_vec, rmatvec(test_vec) 

Shapes:
V11_new: (4, 2)
S11_sqrt: (2,)
S11_invsqrt: (2,)
A12: (4, 2)

First few values:
Upper block first row: [ 0.71005821+0.j  0.12641873+0.j  0.17366092+0.j -0.04376245+0.j]
Lower block first row: [ 1.07491623+0.j  0.1823569 +0.j  0.67237328+0.j -0.56324559+0.j]
(4,)


(array([ 0.76294326+0.j,  0.13123303+0.j,  0.39545515+0.j, -0.30052169+0.j]),
 array([ 0.77520165+0.j,  0.13344486+0.j,  0.39712068+0.j, -0.29965986+0.j]))

In [220]:
 rmatvec(test_vec

(4, 2)

In [213]:
x = test_vec  # use same test vector
x1, x2 = x[:n*w], x[n*w:]
V11_new_t_x1 = V11_new.T @ x1
V11_new_t_A12_x2 = V11_new.T @ A12_x2


NameError: name 'A12_x2' is not defined

In [201]:
G.shape

(6, 4)

In [258]:
test_x = np.random.rand(2*w)
test_y = np.random.rand(N)
svd_matvec(test_x), G @ test_x, svd_rmatvec(test_y), G.T @ test_y

(array([ 0.37120332+0.j,  0.06470874+0.j,  0.15343844+0.j, -0.098921  +0.j,
         0.60527899+0.j,  0.05339998+0.j]),
 array([ 0.37120332+0.j,  0.06470874+0.j,  0.15343844+0.j, -0.098921  +0.j,
         0.60524681+0.j, -0.18533924+0.j]),
 array([ 0.53432257+0.j,  0.08660284+0.j,  0.51777125+0.j, -0.50275517+0.j]),
 array([ 0.53432257+0.j,  0.08660284+0.j,  0.51777125+0.j, -0.50275517+0.j]))

In [188]:
full_matrix

array([[ 0.55223763,  0.09539684,  0.26776385, -0.1950996 ,  0.9277204 ,
        -0.28608835],
       [ 0.09539684,  0.01688533,  0.02783035, -0.01133994,  0.14752528,
        -0.04458751],
       [ 0.26776385,  0.02783035,  0.9661488 , -1.10966305,  1.0278644 ,
        -0.35809511],
       [-0.1950996 , -0.01133994, -1.10966305,  1.30094234, -1.02933859,
         0.36733932],
       [ 0.9277204 ,  0.14752528,  1.0278644 , -1.02933859,  1.95803038,
        -0.63223722],
       [-0.28608835, -0.04458751, -0.35809511,  0.36733932, -0.63223722,
         0.20575552]])

In [182]:
A12_upper

array([[ 0.9277204 +0.j, -0.28608835+0.j],
       [ 0.14752528+0.j, -0.04458751+0.j]])

In [ ]:
U_new, S_new, Vt_new 

In [154]:
# 1. Check dimensions
test_x = np.random.rand(3*w) + 1j * np.random.rand(3*w)
test_y = np.random.rand(2*w) + 1j * np.random.rand(2*w)
assert svd_matvec(test_x).shape == (3*w,)
assert svd_rmatvec(test_y).shape == (2*w,)

# 2. Check adjoint property
# For any vectors x, y: <Ax,y> = <x,A^H y>
x = np.random.rand(2*w) + 1j * np.random.rand(2*w)
y = np.random.rand(3*w) + 1j * np.random.rand(3*w)
lhs = np.vdot(svd_matvec(x), y)
rhs = np.vdot(x, svd_rmatvec(y))
assert np.abs(lhs - rhs) < 1e-10

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 0 is different from 2)

In [102]:
# First (n-1)w rows: V S V^T part
V_old = V[:w, :]  # All but last block

# Compute V S V^T x for all old blocks at once
V_old @ (np.diag(S) @  (V_old.T))

array([[ 4.77307898+0.j, -0.0989312 +0.j],
       [-0.0989312 +0.j,  1.08686079+0.j]])

In [80]:
np.linalg.eig(full_matrix)

EigResult(eigenvalues=array([5.31465   , 2.85310228, 1.67532238, 0.12129793]), eigenvectors=array([[ 0.90863491, -0.292327  , -0.28991035,  0.0698535 ],
       [ 0.05531945,  0.5682878 , -0.20830545,  0.79410174],
       [-0.24129555,  0.09352225, -0.92084635, -0.29167111],
       [-0.33630167, -0.76344449, -0.15685286,  0.52863114]]))

In [81]:
second_window.shape

(2, 4)

In [82]:
U_full @ np.diag(S_full**2) @ U_full.T

array([[24.25157065,  0.23778163, -5.6663736 , -6.68626802],
       [ 0.23778163,  2.84638594,  0.59056766, -3.95927223],
       [-5.6663736 ,  0.59056766,  4.09697058,  2.11399152],
       [-6.68626802, -3.95927223,  2.11399152,  8.01218831]])

In [83]:
V11 @ np.diag(S11) @ V11.T

array([[ 4.77307898+0.j, -0.0989312 +0.j],
       [-0.0989312 +0.j,  1.08686079+0.j]])

In [84]:
aug_matrix @ aug_matrix.T

array([[ 4.77307898+0.j, -0.0989312 +0.j, -0.79845833+0.j,
        -0.90662263+0.j],
       [-0.0989312 +0.j,  1.08686079+0.j,  0.37395491+0.j,
        -1.23105235+0.j],
       [-0.79845833+0.j,  0.37395491+0.j,  0.25132107+0.j,
        -0.26011468+0.j],
       [-0.90662263+0.j, -1.23105235+0.j, -0.26011468+0.j,
         1.61219267+0.j]])

In [104]:
V11_new @ np.diag(S11_new) @ V11_new.T

array([[ 4.63167959+0.j, -0.20683225+0.j, -1.24323588+0.j,
        -0.98728415+0.j],
       [-0.20683225+0.j,  0.93767643+0.j,  0.08069368+0.j,
        -1.33670996+0.j],
       [-1.24323588+0.j,  0.08069368+0.j,  0.33439217+0.j,
         0.22756495+0.j],
       [-0.98728415+0.j, -1.33670996+0.j,  0.22756495+0.j,
         2.26400409+0.j]])

In [100]:
V11_new.shape, S11_new.shape

((4, 2), (2,))

In [105]:
np.linalg.eig(full_matrix)

EigResult(eigenvalues=array([5.31465   , 2.85310228, 1.67532238, 0.12129793]), eigenvectors=array([[ 0.90863491, -0.292327  , -0.28991035,  0.0698535 ],
       [ 0.05531945,  0.5682878 , -0.20830545,  0.79410174],
       [-0.24129555,  0.09352225, -0.92084635, -0.29167111],
       [-0.33630167, -0.76344449, -0.15685286,  0.52863114]]))

In [107]:
S11_new, V11_new

(array([5.31465   +0.j, 2.85310228+0.j]),
 array([[-0.90863491+0.j,  0.292327  +0.j],
        [-0.05531945+0.j, -0.5682878 +0.j],
        [ 0.24129555+0.j, -0.09352225+0.j],
        [ 0.33630167+0.j,  0.76344449+0.j]]))

In [93]:
V[:w, :] @ np.diag(S) @ V[:w, :].T

array([[ 4.77307898+0.j, -0.0989312 +0.j],
       [-0.0989312 +0.j,  1.08686079+0.j]])